# Generated by Django 3.0.3 on 2020-02-29 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgnizationalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='organization')),
                ('address', models.CharField(max_length=500)),
                ('slogan', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_no', models.CharField(max_length=500)),
                ('alt_contact_no', models.CharField(blank=True, max_length=500, null=True)),
                ('map_location', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('about_us', models.TextField()),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('show_popup', models.BooleanField(default=False)),
                ('popup_image', models.ImageField(blank=True, null=True, upload_to='organization')),
                ('facebook', models.CharField(max_length=500)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('featured_photo', models.ImageField(upload_to='organization')),
                ('featured_video_link', models.CharField(max_length=500)),
                ('messenger_script', models.TextField(blank=True, null=True)),
                ('google_analytics_script', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=500)),
                ('contact_no', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/admin/')),
                ('about', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
